backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# Uncomment the line below for local development only
# local_backend: true

media_folder: "public/images/products" # Media files will be stored in the repo under public/images/products
public_folder: "/images/products" # The src attribute for uploaded media will begin with /images/products

collections:
  - name: "products" # Used in routes, e.g., /admin/collections/products
    label: "Products" # Used in the UI
    folder: "content/products" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Product Name", name: "name", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "markdown", required: true}
      - {label: "Price ($)", name: "price", widget: "number", value_type: "float", min: 0, required: true}
      - {label: "Category", name: "category", widget: "select", options: ["Sculptures", "Furniture", "Decorative", "Functional", "Art Pieces", "Custom"], required: true}
      - {label: "Featured Image", name: "featured_image", widget: "image", required: true}
      - {label: "Image Gallery", name: "gallery", widget: "list", required: false, fields: [
          {label: "Image", name: "image", widget: "image", required: true},
          {label: "Alt Text", name: "alt", widget: "string", required: true}
        ]}
      - {label: "Dimensions", name: "dimensions", widget: "string", required: false, hint: "e.g., 12\" x 8\" x 4\""}
      - {label: "Wood Type/Material", name: "material", widget: "string", required: false, hint: "e.g., Oak, Pine, Mahogany"}
      - {label: "Available for Purchase", name: "available", widget: "boolean", default: true, required: true}
      - {label: "Featured Product", name: "featured", widget: "boolean", default: false, hint: "Show on homepage"}
      - {label: "Status", name: "status", widget: "select", options: ["In Stock", "Made to Order", "Sold Out", "Coming Soon"], default: "In Stock", required: true}

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "content/pages/about.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Contact Page"
        name: "contact"
        file: "content/pages/contact.md"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Phone", name: "phone", widget: "string"}
          - {label: "Address", name: "address", widget: "text"}